//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.27 at 02:20:20 PM MSK 
//


package main.schemas.srvprivateoperstate;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PrivateOperStateRs_QNAME = new QName("", "PrivateOperStateRs");
    private final static QName _PrivateOperStateRq_QNAME = new QName("", "PrivateOperStateRq");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrivateOperStateRs }
     * 
     */
    public PrivateOperStateRs createPrivateOperStateRsType() {
        return new PrivateOperStateRs();
    }

    /**
     * Create an instance of {@link PrivateOperStateRq }
     * 
     */
    public PrivateOperStateRq createPrivateOperStateRqType() {
        return new PrivateOperStateRq();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link BankInfoType }
     * 
     */
    public BankInfoType createBankInfoType() {
        return new BankInfoType();
    }

    /**
     * Create an instance of {@link TransferLineInfoType }
     * 
     */
    public TransferLineInfoType createTransferLineInfoType() {
        return new TransferLineInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivateOperStateRs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrivateOperStateRs")
    public JAXBElement<PrivateOperStateRs> createPrivateOperStateRs(PrivateOperStateRs value) {
        return new JAXBElement<PrivateOperStateRs>(_PrivateOperStateRs_QNAME, PrivateOperStateRs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrivateOperStateRq }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrivateOperStateRq")
    public JAXBElement<PrivateOperStateRq> createPrivateOperStateRq(PrivateOperStateRq value) {
        return new JAXBElement<PrivateOperStateRq>(_PrivateOperStateRq_QNAME, PrivateOperStateRq.class, null, value);
    }

}
