//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.27 at 02:20:20 PM MSK 
//


package main.schemas.srvprivateoperstate;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SPName_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SPName_Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BP_ES"/>
 *     &lt;enumeration value="BP_VSP"/>
 *     &lt;enumeration value="BP_ERIB"/>
 *     &lt;enumeration value="BP_COD"/>
 *     &lt;enumeration value="BP_ESK"/>
 *     &lt;enumeration value="BP_IASK"/>
 *     &lt;enumeration value="BP_WAY"/>
 *     &lt;enumeration value="BP_BS"/>
 *     &lt;enumeration value="BP_INFOBANK"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-autopay"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-hubble"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-wzext"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-ufs"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-ufs:erkc"/>
 *     &lt;enumeration value="urn:sbrfsystems:99-crm"/>
 *     &lt;enumeration value="BP_KZUPD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SPName_Type")
@XmlEnum
public enum SPNameType {


    /**
     * ���������� ���������������� (����������)
     * 
     */
    BP_ES("BP_ES"),

    /**
     * �� ���
     * 
     */
    BP_VSP("BP_VSP"),

    /**
     * �� ���� ��� �������� ��������
     * 
     */
    BP_ERIB("BP_ERIB"),

    /**
     * �� ���
     * 
     */
    BP_COD("BP_COD"),

    /**
     * �� ���
     * 
     */
    BP_ESK("BP_ESK"),

    /**
     * �� ����
     * 
     */
    BP_IASK("BP_IASK"),

    /**
     * �� WAY4U
     * 
     */
    BP_WAY("BP_WAY"),

    /**
     * �� ��
     * 
     */
    BP_BS("BP_BS"),
    BP_INFOBANK("BP_INFOBANK"),
    @XmlEnumValue("urn:sbrfsystems:99-autopay")
    URN_SBRFSYSTEMS_99_AUTOPAY("urn:sbrfsystems:99-autopay"),
    @XmlEnumValue("urn:sbrfsystems:99-hubble")
    URN_SBRFSYSTEMS_99_HUBBLE("urn:sbrfsystems:99-hubble"),
    @XmlEnumValue("urn:sbrfsystems:99-wzext")
    URN_SBRFSYSTEMS_99_WZEXT("urn:sbrfsystems:99-wzext"),

    /**
     * �� ���
     * 
     */
    @XmlEnumValue("urn:sbrfsystems:99-ufs")
    URN_SBRFSYSTEMS_99_UFS("urn:sbrfsystems:99-ufs"),

    /**
     * �� ��� (���������� ����)
     * 
     */
    @XmlEnumValue("urn:sbrfsystems:99-ufs:erkc")
    URN_SBRFSYSTEMS_99_UFS_ERKC("urn:sbrfsystems:99-ufs:erkc"),
    @XmlEnumValue("urn:sbrfsystems:99-crm")
    URN_SBRFSYSTEMS_99_CRM("urn:sbrfsystems:99-crm"),
    BP_KZUPD("BP_KZUPD");
    private final String value;

    SPNameType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SPNameType fromValue(String v) {
        for (SPNameType c: SPNameType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
