//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.27 at 02:20:20 PM MSK 
//


package main.schemas.srvprivateoperstate;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for State_Type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="State_Type">
 *   &lt;restriction base="{}String">
 *     &lt;enumeration value="NO_CONTRACT"/>
 *     &lt;enumeration value="ACTIVE_CONTRACT"/>
 *     &lt;enumeration value="CLOSED_CONTRACT"/>
 *     &lt;enumeration value="NOT_SIGNED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "State_Type")
@XmlEnum
public enum StateType {


    /**
     * ������� �� ��������
     * 
     */
    NO_CONTRACT,

    /**
     * ������� ��������
     * 
     */
    ACTIVE_CONTRACT,

    /**
     * ������ �������
     * 
     */
    CLOSED_CONTRACT,

    /**
     * ���������������
     * 
     */
    NOT_SIGNED;

    public String value() {
        return name();
    }

    public static StateType fromValue(String v) {
        return valueOf(v);
    }

}
